#
# 6D localization configuration for the Nao humanoid with laser head
#

odom_frame_id: "world"
base_frame_id: "openni_depth_optical_frame"
 # raycasting (slow) or endpoint model (approx)
use_raycasting: true
use_imu: false

# for testing only!
# weight_factor_roll: 0.0
# weight_factor_pitch: 0.0
#weight_factor_z: 5.0


num_particles: 500
init_global: false
init_from_truepose: false

# global loc:
# num_particles: 20000
# init_global: true
# init_from_truepose: false

# rel. number of effectice particles for resampling threshold (0: never, 1: always)
neff_factor: 1.0 

# minimum weight for a particle (normal scale, need to sum up to < 1!)
# Warning: this keeps the particles from converging properly!
#min_particle_weight: 0.000001

num_sensor_beams: 24
temporal_sampling_range: -0.6
#transform_tolerance: 10.0

# min traversed odometry interval between laser measurements:
# 
update_min_trans: 0.2
update_min_rot: 0.4

# laser obs. model (for raycasting only)
raycasting/z_hit: 0.8
raycasting/z_short: 0.1
raycasting/z_max: 0.05
raycasting/z_rand: 0.05
raycasting/sigma_hit: 0.05
raycasting/lambda_short: 0.1

# laser obs.model (for endpoint model only)
# std.dev for gaussian (p_hit)
#use in loc
endpoint/sigma: 0.25
#used for global:
#laser_endp_sigma: 0.07


#motion_mean_z: 0.317
#motion_range_z: 0.03
#motion_range_roll: 0.25
#motion_range_pitch: 0.1

motion_sigma_z: 0.2
motion_sigma_roll: 0.00015 # 0.85 deg.
motion_sigma_pitch: 0.00015 # 0.85 deg.

motion_noise/x: 0.18    # per m
motion_noise/y: 0.18    # per m
motion_noise/z: 0.68   # per m
motion_noise/roll: 0.04    # per m
motion_noise/pitch: 0.04    # per m
motion_noise/yaw: 0.04    # per m

# initial pose (when no truepose available):
initial_pose/x: -0.4
initial_pose/y: 4.0
initial_pose/z: 1.0     # over z-plane 
initial_pose/roll: 3.14
initial_pose/pitch: 0.0
initial_pose/yaw: 0.0    

# std dev for initial noise (truepose or manual init)
initial_std/x: 0.10
initial_std/y: 0.10
initial_std/z: 0.50
initial_std/roll: 1.1
initial_std/pitch: 1.33
initial_std/yaw: 1.3    # ~13 deg
